=pod

=encoding utf-8

=head1 NAME

jukebox-layouts - Layout documentation for jukebox

=head1 DESCRIPTION

=head2 Introduction

The L<jukebox(1)> interface is defined by layouts.  Each layout
define a window that contain several containers, each containing
widgets.

Layouts are used in many places in jukebox: the main window, the
"traytip" popup, the fullscreen mode, the search and browser windows,
pages that can be inserted as a tab, desktop widgets (plugin), the
titlebar overlays (plugin), as well as some internal windows (such as
the queue, equalizer).

Note that this documentation is likely incomplete, and could be
improved.  Don't hesitate to suggest improvements, ask for
clarification, or point out missing information.

=head2 Advice for testing layouts

Experimenting with layouts is highly encouraged.  When doing so, it is
recommended to launch jukebox from the command-line as some layout
errors can be printed on the terminal.  A good way to do that is
launch jukebox with the B<-layout> (or B<-l>) followed by the layout
identifier, this will directly open the desired layout.

You can then easily quit without saving by pressing B<C-c> in the
terminal, an advantage of this exit method is that it always works (no
matter what your layout contains) and that no setting for the layout
will be saved, so that you can see it each time as a new user would.
Note that the auto-save plugin might still save the options, the
B<-demo> option will prevent any writing of the I<jukeboxrc>.  You can
also use a copy of your I<jukeboxrc> file and use the B<-cfg> option
to tell B<jukebox> to use the copy.

=head2 Layout files

Layouts are defined using text files, each file can contain one or
more layout.  Layout files use the I<.layout> extension, they are
found in 2 places:

=over

=item I</usr/share/jukebox/layouts/>

The default layouts included with jukebox.

=item I<$XDG_CONFIG_HOME/jukebox/layouts/>

Custom layouts that can be added by putting them in
I<$XDG_CONFIG_HOME/jukebox/layouts>, which can be either a file or a folder
containing multiple I<.layout> files (read in alphabetical order).

=back

=head2 Layout syntax

A layout definition begins with a line containing a layout identifier
enclosed in square brackets (B<[]>) such as: B<[some_layout_id]>.

Layout files may also contain group and column definitions for the
SongTree widget.  These definitions begin with lines
between B<{}>.  The definitions include all the following lines up to
the next B<[]> or B<{}> line, or to the end of the file.

Layout definition syntax:

    [layout_id]
    key1 = value
    key2 = value
    ...

C<layout_id> is the string used to identify the layout.  It can contain
spaces or other special characters but it is recommended that only
alphanumeric characters (C<A-Z>, C<a-z>, C<0-9>, and C<_>) be used,
otherwise it may harder or impossible to use the layout with some
advanced features.  If you want to give the layout a nice name use the
C<Name> property explained below.

Long lines can be be split into multiple lines by ending them with a
backslash (the backslash is optional as long as the next line doesn't
begin with something like C<word=>).
Keys define either containers or properties, they only use simple
alphanumeric characters: C<A-Z a-z _ 0-9>.
Keys are unique for a layout, duplicate key definitions replace the
previous one.

If the name of the key begins with one of : HB, VB, HP, VP, MB, EB,
TB, FR, NB (and some others, see below) the key is the name of a
container that will contain widgets (also called layout elements or
controls) or other containers.
For containers the value is a list of children (widgets and/or other
containers), separated by a space and preceded by optional packing
options.  The widget names can be followed by a number (to have
multiple widgets of the same name) and its options between
parentheses.

There must be one, and only one, container which has no parent, this
container will be put in the layout window.

=head3 B<Simple examples>

Very simple example, with 3 buttons (settings, play/pause, and open
browser window) and the current song title:

    [very_simple]
    Type = G
    HBox = Pref Play OpenBrowser _Title

Type=G (G for generic) is used to make it appear in the player layouts
list in the settings dialog.  The C<_> before C<Title> is used to make C<Title> use all the available space in the horizontal box (HBox) it is
packed in.  The 4 widgets are put into a HB (= horizontal box)
container, so they will be placed in a line.

    [simple]
    Type=G
    VBmain = MBmenu HBbuttons Title Text(markup="<i>by</i> $artist <i>in</i> $album")
    MBmenu = MainMenuItem
    HBbuttons= Prev Play Next

This layout has 3 containers, C<VBMain> being the parent widget for
C<MBmenu> and C<HBbuttons>.  The C<Title> widget displays the current
song's title and C<Text> has an option that defines what it should
display, complete with
L<pango markup|http://developer.gnome.org/pango/stable/PangoMarkupFormat.html>
and L</Song variables>.  This layout will show, vertically: a menu,
buttons, title, and the text widget showing artist and album.

Look in the layouts files (installed in F</usr/share/jukebox/layouts/>)
for more examples.

=head2 Normal containers

Containers are used to organize the widgets inside the window.  They
accept options that must be specified in parenthesis before the child
widgets list.  For example:

    HBname = (option1=value1,option2=value2) widget1 widget2

All containers accept the option C<border> to specify the amount of
padding around the container.

=over

=item B<HB/VB>

Horizontal/Vertical Boxes (based on
L<GtkBox|http://developer.gnome.org/doc/API/2.0/gtk/GtkBox.html>
).

These containers group widgets horizontally or vertically.  Optional
packing options are:

=over 2

=item * a number

padding (in pixels)

=item * an underscore C<_>

expand (the widget will use all remaining space in the container)

=item * a dash C<->

right aligned

=item * a dot C<.>

fill (rarely needed)

=back

Example:

  HBname = 2_-widget1(opt1=val,opt2=val) -widget2 2container3

Cover and ArtistPic widgets are treated specially, they ignore the
expand mode, and expand until they reach a square size.  For instance,
in a HBox which has a height of 30, a Cover widget will use available
space to expand if it has a width less than 30.

Note that the maxwidth and maxheight widgets options only work inside
a HB and a VB respectively.

=item B<HP/VP>

Horizontal/Vertical Panes (based on
L<GtkPaned|http://developer.gnome.org/doc/API/2.0/gtk/GtkPaned.html>
)

Same as HB/VB but they contain only 2 widgets.

They only have one packing option, the underscore C<_>.  It sets the
expand property that tells the container that this widget should give
or receive space when the container is resized.  

If both children have the expand property, they will both give or
receive space when the container is resized.

=item B<TB> (I<deprecated>)

Notebook (based on
L<GtkNotebook|http://developer.gnome.org/doc/API/2.0/gtk/GtkNotebook.html>
).

Each widget is in a tab, no packing options but the syntax is a bit
different, each widget is preceded by the tab title.

The title can have spaces by using quotes, for example:

    TBname = title1 widget1(options) "title with spaces" widget2(options) title3 container3

=item B<NB> (I<new version>)

Notebook (based on
L<GtkNotebook|http://developer.gnome.org/doc/API/2.0/gtk/GtkNotebook.html>
).

No packing options, syntax is simply the list of children.

A title and an optional icon is given by children options C<tabtitle>
and C<tabicon>.  For example:

    NBname = widget1(tabtitle="a title",other_option=value) widget2(tabtitle="other tab",tabicon=gmb-list) widget3(tabtitle=third)

Tab position and rotation can be set by using C<tabpos> option, which
can be one of left, right, top, or bottom, optionally followed by an
angle : 0, 90, 180 or 270.

Example:

    NBname = (tabpos=left90) children1 children2

The C<hidetabs=1> container option can be used to hide the tabs, this
is meant to be used with commands that use SetFocusOn to change the
visible page/child.

As this container is in fact a TabbedLists/Context with different
default options, it also accept the TabbedLists/Context widget
options.

=item B<EB>

Expander (based on
L<GtkExpander|http://developer.gnome.org/doc/API/2.0/gtk/GtkExpander.html>
).

Contains only one child, that child can be shown/hidden by clicking on
the expander.

Option: C<label> sets the text that will be displayed next to the
expander.

Examples:

    EBname = (label="optional label") widget1
    EBsimple = widget2

=item B<FB>

Fixed (based on
L<GtkFixed|http://developer.gnome.org/doc/API/2.0/gtk/GtkFixed.html>
).

Each widget is positioned at precise coordinates.

Syntax:

    FBname = x1,y1 widget1 x2,y2,w2,h2 widget2 ...

The widget is positioned at the x,y coordinate.

An optional width and height can follow the coordinates, to specify
how much space the widget should use.  An height or width of 0 means
leave it as default.

x,y,w,h can be relative to the width/height of the container by
preceding the number with a dot (C<.>).

x,y can be relative to the right/bottom border by prefixing it with
minus (C<->).

=item B<MB>

Menu Bar.

They can only contain MenuItem widgets or SM containers, no packing
options.

=item B<SM>

Submenu.

They can only contain MenuItem widgets or SM containers, no packing
options, label is set with the C<label> container option.

=item B<BM>

Button menu.

They can only contain MenuItem widgets or SM containers, no packing
options.

Container options:

=over

=item label

set the button label

=item icon

set an icon

=item relief

(default to none) button relief

=item size

(default to menu) size of the icon

=back

=item B<FR>

Frame (based on
L<GtkFrame|http://developer.gnome.org/doc/API/2.0/gtk/GtkFrame.html>
).

Draw a border around its child, with an optional label.
(Can only contain one child).

Container options:

=over

=item shadow

one of C<none>, C<in>, C<out>, C<etched-in> (default), C<etched-out>

=item label

optional text of the frame label

=back

=item B<SB>

Scrolled window (based on
L<GtkScrolledWindow|http://developer.gnome.org/doc/API/2.0/gtk/GtkScrolledWindow.html>
).

Adds scrollbars to its child.
(Can only contain one child).

=item B<AB>

Alignment (based on
L<GtkAlignment|http://developer.gnome.org/doc/API/2.0/gtk/GtkAlignment.html>
).

Controls the alignment and size of its child.
(Can only contain one child).

Container options :

=over

=item xalign

Horizontal position of child in available space, value between 0(left)
and 1(right), default to .5 (center)

=item yalign

Vertical position of child in available space, value between 0(top)
and 1(bottom), default to .5 (center)

=item xscale

If available horizontal space is bigger than needed for the child, how
much of it to use for the child. 0.0 means none, 1.0 means all
(default to 1)

=item yscale

If available vertical space is bigger than needed for the child, how
much of it to use for the child. 0.0 means none, 1.0 means all
(default to 1)

=back

=item B<WB>

Event window.

This container is used to have control over the background or mouse
events on its child.
(Can only contain one child).

Some containers and widgets (like HB/VB) do not have their own
gdkwindow and thus can't control their background or mouse events.
Putting them inside a WB allows working around that.

For example for having a window pop-up when the mouse is above a HB
container, using the C<hover_layout> option on the HB won't work, but
putting the HB inside a WB and using the C<hover_layout> option on the
WB will work.  It's also a way to paint the background of a HB using a
custom GTK theme.

=back

=head2 Special containers

There is also 2 special containers, widgets in these containers must
belong to a normal container, and as the widget is defined elsewhere,
widgets options can not be set here.  These containers can be viewed
as layout properties that take a list of widgets as value.

=over

=item B<HSize/VSize>

Size groups (see
L<GtkSizeGroup|http://developer.gnome.org/doc/API/2.0/gtk/GtkSizeGroup.html>
).

Force all widgets to have the same Horizontal/Vertical size, if the
list of widgets begin with a number, the first widget
Horizontal/Vertical size will be set to this number (in pixels).

Example:

    HSize0 = 20 widget1 widget2
    HSize1 = widget3 widget4

=item B<VolumeScroll>

A unique virtual container (must be the exact name).  For all widgets
or containers inside, the scroll wheel will modify the volume (unless
the scroll event is intercepted, like in a scrollable list).

Example:

    VBmain= Title HBbuttons TimeBar
    HBbuttons= Pref Play
    VolumeScroll= Title HBbuttons

=back

=head2 Layout properties

=over

=item B<Title>

Set a title for the window.  If not set, the window title defaults to
C<Song Title by Artist> (B<%S> by B<%a>)
(see L</Song variables>).

    Title = jukebox playing %S by %a from %l

=item B<Type>

A string of letters, usually one letter, defining the type or types of
a layout.  Recognized values include C<G> (generic/player), C<B>
(browser), C<T> (tray), C<F> (fullscreen), C<S> (search), C<P> (page
for C<TabbedLists>, C<NB>, or C<Context>), C<O> (titlebar overlay),
C<D> (desktop widget), and C<K> (karaoke).


Layouts of type G may optionally be followed a plus sign C<+> that will
make the layout appear in the LayoutItem sub-menu.  This should only
be used by layouts that include a LayoutItem.  The idea is that users
must be able to switch between the different '+' layouts easily.

Layouts work perfectly fine without a type, layouts without a type
are simply not listed in the GUI.  They can still be opened
with the C<OpenCustom> command or with the C<-layout> command-line
option.

=item B<Name>

Set the name of the layout displayed in the settings dialog.  The
default Name is the layout id.

Contrary to the layout id, the Name can be changed without losing the
layout's saved settings (window size, ...).

The name can be marked as translatable by using the syntax

  Name=_"name of the layout"

=item B<Title and Icon>

Used to define a tab title and a tab icon if the layout is used as a
page in a NB/TabbedLists/Context

=item B<Default> (I<mostly deprecated>)

Default options used when the layout has no saved state, contains a
space-separated list of keys and values, by pair,
C<widget_or_container_name widget_or_container_variable_options>.

There is a special key: Window, for the window properties, see the
Window layout property below.

Example:

    Default = Window size=1120x820,sticky=0 HPbig 780 FPane0 page=artist

This is mostly deprecated as now default options can be specified
among the normal widget options, but it is still used a bit, in
particular for HP/VP containers.

=item B<KeyBindings>

Pairs of keys and action, example:

    KeyBindings = Insert OpenSearch c-q EnqueueSelected c-Insert OpenCustom(a_layout_id)

Key names are as shown in the key binding tab in the settings dialog.

Modifiers are one lower case letter: B<c> for ctrl, B<s> for shift,
B<a> for alt and B<w> for win/super.

The modifier(s) and key name can be preceded by a '+' to make the
shortcut a higher priority than the normal shortcuts for the focused
widget (example: "+c-f" for a ctrl-f that overrides the default B<C-f>
action of some widgets).  B<Warning>: It may breaks some features or
the keyboard navigation.

Commands can be found by running jukebox with command-line option
C<-listcmd>.

=item B<DefaultFocus>

Set which widget gets the initial focus in the window.

Some complex widgets do not accept initial focus; in that case the
property has no effect for that widget.

Example:

    HBmain= Pref Play _Title
    DefaultFocus= Play

=item B<DefaultFont> and B<DefaultFontColor>

Set a default font and font color for widgets that use a font or a
color option.

=item B<SkinPath> and B<SkinFile>

Used to select an image file for layout skinning and window
backgrounds.  Bundled layouts provide examples of the supported
syntax.

=item B<Window>

Set some window options:

=over

=item - B<pos> and B<size>

Set the default size and position of the window, format is
B<number>xB<number>, values can be relative by using a B<%>.
For example:

    pos=0x20

or

    pos=50%x20%

If a percentage is used for B<pos>, the window will be centered on
this position by default.  This can be changed by appending a
percentage relative to the size of the window.

For example, B<pos=50%-50%x0+10%> will put the window at
B<x = screenwidth/2 - windowwidth/2> and B<y = 0 + windowheight/10>.

=item - B<fixedsize>

Set a fixed size for the window, -1 means the normal minimum
width/height of the window.

Example:

  fixedsize=200x-1

=item - B<typehint>

Set the window type hint passed to GTK.  Window managers may use this
hint to decide how a window should be managed.  For example, a compact
tool window can use:

  typehint=utility

=item - B<transient>

If set to 1, make the window transient for the main jukebox window.
This is appropriate for auxiliary windows whose useful context is the
main player window, and allows window managers to manage them as such.

=item - B<sticky>, B<ontop>, B<below> and B<fullscreen>

Can be set to 1 (true) or 0 (false).

Note that it only sets the default, if this window property is changed
by the user it will be saved.

=item - B<insensitive>

If set to 1, makes the window completely insensitive to mouse or
keyboard.

=item - B<transparent>

If set to 1, makes the window background transparent
(requires B<Cairo> perl module and a compositing window manager to work).

=item - B<shape>

When used with a background skin and with the B<transparent=1> option,
it will make the window "transparent to input" where the alpha value
is inferior to the shape option.

Example:

  Window = transparent=1, shape=10

=item - B<opacity>

Value is a number between 0 and 1, requires a compositing window
manager.

=item - B<dragtomove>

If set to 1 the window can be moved by clicking on an empty area of
the window.

=item - B<uniqueid>

A string, default to layout id, used by the option B<ifexist>.

Note that this option is overridden for the usual windows (player,
browser, search, ...), but can be used at least with the B<OpenCustom>
command.

=item - B<ifexist>

Define the action to take when attempting to create a window with the
same B<uniqueid> as an existing window, it can be one of:

=over

=item toggle

close existing window

=item present

bring the existing window to the front

=item replace

close the existing window and open a new window

=back

=back

=back

=head2 Derived Layouts

A layout can be derived from a previously defined layout by adding
C< based on >, followed by the layout id of the layout it is based on:

    [layout_id] based on this_other_layout_id

In this case the layout starts with all the key definitions of the
other layout, each key can be re-defined or deleted (if nothing
follows the B<=>).
This method of deriving layouts is only recommended for very small
variants where only one or two line changes, as it might easily break
if the original layout changes.

=head2 Widgets

=head3 Widgets options

Widget options are specified in the layout definition, in parentheses,
after the name of the widget.  Options are a list of keywords and
values, separated by commas (with optional spaces).  For example:

    VBmain= widget1(key1=value1,key2=value2, key3=value3) widget2(anotherkey=somevalue)

There are 2 kind of widget options.  The first one (let's call them
B<layout-set> options) are the options that can only be set in the
layout definition, most of the options described in this document are
of this kind.  The second kind (let's call them B<user-set> options)
are the options that the user can change in the GUI and are saved when
the window is closed.  The layout definition can change the default
value of the user-set options, but if the user has already used the
layout once, the user-set options will use their last recorded value
and ignore the value set in the layout definition.  As mentioned
earlier, you can use the B<-demo> command-line option to prevent the
user-set options from having a recorded value and be able to test the
value set in the layout definition.

Most of these user-set options are not documented here.  To discover
them you just need to use the widget in a layout and then look at the
file containing the saved options (F<$XDG_CONFIG_HOME/jukebox/jukeboxrc>) for
the line containing the layout id, then for the line containing the
widget name, the following lines contain the saved widget options.
Some of these options may contain sub-options (for example a
B<FilterPane> has a set of sub-options for each of its page), a
default for these sub-options can be set in the layout by using a
slash (B</>) to separate option and sub-option.  Example:

  FilterPane(page_album/mode=mosaic)

In the future, some of the layout-set options may become user-set
options, as more options are exposed to the GUI.

=head3 Generic widget options

A number of options work on a lot of widgets and containers.

=over

=item B<size options>

=over

=item - B<minwidth> and B<minheight>

Specify a minimum width or height, will not work on some widget.

=item - B<maxwidth> and B<maxheight>

Only works if the widget is inside of a B<HB>/B<VB> container, specify
a maximum expansion width or height.

=item - B<expand_weight>

Default to 1, used to specify a higher priority to get extra space
from a B<HB>/B<VB>.

=back

=item B<click options>

A lot of widgets, in particular text labels, indicators and buttons
can use the option B<click1> (or B<click2> ...) to (re)define the
action executed when the widget is clicked with mouse button 1
(or 2 ...).  Example:

  Play(click2=OpenSongProp)

Button widgets also accept the option B<activate> to (re)define the
action executed when the button is activated with a mouse click or
keyboard.

=item B<tip option>

A lot of widgets, in particular labels, indicators and buttons can use
the option B<tip> to define a tool-tip for the widget.  The tip may
contain L</Song variables> to display information
on the current song.  Example:

  Title(tip="last played : $lastplay")

=item B<cursor option>

Another common option, it is used to change the mouse cursor when it
hovers over the widget.  Example:

  Play(cursor=hand2)

See L<Gtk2::Gdk::Cursor|https://metacpan.org/pod/Gtk2::Gdk::Cursor>
for a list of cursor names.

=item B<hover_layout option>

Many widgets and containers can use the
B<hover_layout=ALayoutName> option.  It causes a window using the
B<ALayoutName> layout to pop-up when the mouse hover on the widget
(for more than 1000ms, or the value set by the B<hover_delay> option,
use 1000ms if set to 0).  The popped-up window disappear when the
mouse exit the window.

Only the widget or container that have their own gdkwindow can use
this option.  For the other widgets/containers, they can be placed
inside a B<WB> and use the B<hover_layout> option on this B<WB>.

The B<hover_layout_pos> option can used to control the position of the
popped window relative to the triggering widget.

Simple example of the B<hover_layout> option to popup a big cover when
the mouse hover on a Cover widget, by defining the Cover widget with
this option: B<Cover(hover_layout=CoverPopup)>, where B<CoverPopup> is
the layout:

    [CoverPopup]
    VBmain= Cover(minsize=800,maxsize=800,click1=CloseWindow)

To make the layout popup when the Cover widget is clicked rather than
hovered, use this option:

  Cover(click1=PopupCustom(CoverPopup))

=item B<group option>

The B<group> option is used to link a widget to a B<songlist>
(or equivalent widget) or to a song or set of songs.  There are 2 type
of links associated with the group option (they will be separable in
the future), links to 1 song (like the current song or the last
clicked song in a B<songlist>), and the links to a set of songs (like
the playlist or the content of a B<songlist>), most widgets only use
one type of links, some use both.

If the group option is not specified, most filter-oriented widgets
(like B<songlist> and B<FilterPane>) will use a default group, local
to the window.  The song-oriented widget will often default to the
group Play (like the Title/Artist/... widgets) to follow the current
song.  Group names that begin with an upper-case letter are global,
the others are local to the window.  There are a few special
predefined groups:

=over

=item - Play

Links to the current song or the playlist.

=item - Next or NextN

Link to the next song or the (N+1)th next song.  The next song can be
undefined, in particular when in a random weighted mode.

=item - Recent or RecentN

Link to the previously played song or the (N+1)th previously played
song.

=back

Examples:

=over

=item *

Linking 2 FilterPane a SimpleSearch and a Total widget with a SongList
(if there is no other songlist-like widget in the layout, using the
group option is not needed as the default group will do fine):

  VBmain= HPfilterpanes SimpleSearch(group=1) _SongList(group=1) Total(group=1)
  HPfilterpanes= FilterPane1(group=1,nb=1) FilterPane2(group=1,nb=2)

=item *

Title widget that display the next song's title:

  Title2(group=Next, markup_empty="<i>no next song</i>")

=item *

Making a Text widget display the title and artist of the song selected
in a SongList:

  VBox= Text0(group=mygroup, markup="$title by $artist", markup_empty="<i>no selected song</i>") _SongList(group=mygroup)

=back

=item B<Options common to the text widgets>

The text widgets (sometimes called label widgets) include:
Title, Title_by, Album, Artist, Comment, Year, Length, PlayingTime,
Pos, and Text

=over

=item - font

Change the default font, the value use the
L<Pango font description syntax|https://docs.gtk.org/Pango/type_func.FontDescription.from_string.html>,
for example: C<12>, C<Sans Italic 12>, C<Monospace>.

(Note that the font for a part of the string can be set in pango markup)

=item - color

Set the default font color, value is an RGB color specification such
as C<#00FF00> or a color name such as C<red>.

(Note that the color for a part of the string can be set in pango markup)

=item - minsize

If set (it is set by default for Album, Artist, Comment, Title, Title_by),
the label will request a minimum width (it can have more if packed
with the expand option in a container), if the width is not enough to
display the text, the text will scroll on mouse-over.  The value of
the B<minsize> option is the width it will request, the unit is in
pixels if followed by a B<p> or in the width of the B<X> character if
it is only a number.

=item - markup

Can be used to re-define the text displayed, you can use
L</Song variables> (like B<%t>, B<%a>, ...) for
current-song dependent text, and
L<Pango markup|https://docs.gtk.org/Pango/pango_markup.html>
(like B<< <b>...</b> >>) for formatting.

=item - markup_empty

For B<Text>, B<Title>, B<Artist>, etc, widgets, define what to display
if there is no current song (or if there is no selected song in the
group they are linked to).  Most of time this default to an empty
string, B<Title> defaults to B<< <Empty playlist> >>.

=item - xalign

Horizontal alignement as a value between 0 (left) and 1 (right),
.5 being center.

=item - yalign

Vertical alignement as a value between 0 (up) and 1 (bottom),
.5 being center.

=item - expand_max

Same as the B<maxwidth> option (specify a maximum expand width when
inside a B<HB>) but the widget will never grow wider than what is
needed to display the string (replace the B<maxwidth> value, so using
the B<maxwidth> with it will have no effect).

=back

=back

=head3 Text widgets

=over

=item - Title

Display currently playing Title.

=item - Title_by

Display currently playing Title and Artist.

=item - Album

Display currently playing Album.

=item - Artist

Display currently playing Artist.

=item - Comment

Display comment of currently playing song.

=item - Year

Display year of currently playing song.

=item - Length

Display length of currently playing song.

=item - Pos

Display position of currently playing song in the playlist.

=item - Text

Display custom text (other text widgets can use these options too to
change their defaults).

=over

=item - text

Label text.

=item - markup

Text than can include
L</Song variables> and
L<Pango markup|https://docs.gtk.org/Pango/pango_markup.html>.

=item - ellipsize

Can be B<none>, B<start>, B<middle>, or B<end>.  Default is B<none>.

Note that enabling ellipsize will make the widget require very little
width, so you need to either force a bigger width request
(option B<minwidth>), or pack the widget in a way that will give it
additional width (such as using the expand option in a B<HB>, provided
the B<HB> gets enough width).

=back

=back

Many of these widgets are simply a B<Text> widget with a set of
default options, in particular the options: B<markup>, B<click1>,
B<click3>, B<minsize>.

=head3 Buttons widgets

=over

=item - Next

Next button.

=item - Play

Play/Pause button.

=item - Prev

Previous button.

=item - Stop

Stop button.

=item - Quit

Quit button.

=item - Repeat

Button to change repeat mode.

=item - OpenContext

Button to open context window.

=item - OpenBrowser

Button to open Browser window.

=item - Pref

Button to open Settings window.

=item - ChooseAlbum

Open a window to select an album.

=item - OpenQueue

Open a queue window.

=item - Fullscreen

Button to switch to/from fullscreen mode.

=item - ChooseRandAlbum

Button to select an album at random, option B<action> can be
B<playlist>, B<addplay>, B<insertplay>, B<queue>, B<replacequeue>, ...
see B<action> option in B<SongList>.

=item - Choose

Button to open a search window.

=item - Button

Custom button (other buttons can use these options too).

=over

=item - text or label

Text in the button.

=item - stock

Icon name, see F</usr/share/jukebox/pix/> or
L<Gtk2 Stock-Items|http://developer.gnome.org/doc/API/2.0/gtk/gtk-Stock-Items.html>
or F<$XDG_CONFIG_HOME/jukebox/icons/> (without filename extension).

=back

=item - ExtraButtons

Placeholder for extra buttons provided by plugins or activated in the
preferences.  Options are passed to the buttons, generic button
options such as size and relief should work, example:

  HButtons= Play Stop ExtraButtons

or

  HButtons= Play(size=menu) Stop(size=menu) ExtraButtons(size=menu)

The OpenContext, OpenBrowser and OpenQueue buttons accept the option
'toggle', if true (=1) the button will close the opened window if it
is already opened.

=back

All buttons can be changed to an indicator (no button border, smaller)
with the option C<button=0>.

Relief can be changed for buttons by using the option C<relief=none>
(default), C<half> or C<normal>.

Size of buttons and indicators can be set by setting the option
C<size> to C<menu>, C<small-toolbar>, C<large-toolbar>, C<button>,
C<dialog>, C<dnd> (the actual size depends on gtk settings).

=head3 Indicators widgets

=over

=item - Filter

Playing filter indicator.

=item - Queue

Queue indicator.

=item - Sort

Sort mode indicator.

=item - LockAlbum

Album lock.

=item - LockArtist

Artist lock.

=item - LockSong

Song lock.

=item - EventBox

Same as Button with default option C<button=0>.

=back

All indicators can be changed to buttons with the option C<button=1>.
Size can be changed same as buttons, see above.

Indicators (Filter Queue Sort ...) and
some buttons (Play Next Prev Stop Quit ...) have a few common options:

=over

=item - C<with_text>

Set to 1 to activate icon-with-text mode.

=item - C<text>

To change the default text.

=item - C<ellipsize>

Set to start/middle/end to activate ellipsize mode, better used with a
B<minwidth> option or when packed in expand mode.

=item - C<markup>

Can be used to set the pango markup that will be used to display the
text, and also add text to the default text.  C<%s> is replaced by the
default text.  Default to C<< <small>%s</small> >> for widgets with
C<size=menu>, else to C<%s>.

=item - C<stock>

Change the default icon by name.  Bundled icons are available under
F</usr/share/jukebox/pix/> and user icons may be placed under
F<$XDG_CONFIG_HOME/jukebox/icons/>.

=back

=head3 Time widgets

=over

=item - PlayingTime

Display position of currently playing song.

=over

=item - markup_stopped

Markup to use when stopped (default is C<--:-->).

=back

=item - Time

Displays XX:XX of XX:XX, format can be redefined with options
B<markup> and B<markup_empty> (and initsize to request enough size
from the start).  C<%s> is replaced by the current playtime, example:

  LabelTime(markup="%s / $length", initsize="XX:XX / -XX:XX")

=item - TimeSlider

Playing position slider.

=over

=item - step_mode

If 1, clicking on the slider advance or or move back the position by
one step, rather than jumping to the clicked position.

=back

=item - TimeBar

Playing position progress bar.

=over

=item - text

Specify a text to display inside the bar, it can contain
L</Song variables>, in addition these variables are
available: C<$percent>, C<$current>, C<$left>, C<$total>.

=item - text_empty

Used instead of text when no song is selected.

=item - ellipsize

Used to ellipsize the text, default to C<end>, can be C<none>,
C<start>, C<middle>, or C<end>.

=item - font

Set the font.

=back

=back

=head3 Volume widgets

=over

=item C<VolumeIcon>

Volume indicator.

=item C<VolumeSlider>

Volume slider.  Useful options include:

=over

=item C<hide>

Hide the numeric value when true.

=item C<horizontal>

Use horizontal orientation when true.

=item C<step_mode>

When true, clicking the slider changes the volume by one step instead
of setting it directly from the clicked position.

=back

=item C<VolumeBar>

Volume progress bar.

=item C<Volume>

Current volume displayed as text.

=back

=head3 Widgets related to the current song

By default these widgets follow the currently playing song.  The
C<group> option can bind supported widgets to another song context, for
example a selected row in a song list:

  VBexample = _SongList(group=example) Cover(group=example)

=over

=item C<Cover>

Display the album cover.  Options include:

=over

=item C<forceratio>

Request a square size when true.  This is useful in pop-up layouts that
cannot resize themselves.

=item C<minsize>, C<maxsize>

Minimum and maximum picture size.  The default maximum is 500.

=item C<default>

Fallback image when no album cover is available.

=item C<overlay>

Draw an overlay on top of the picture.  The format is
C<XxY:WIDTHxHEIGHT:FILE>; the coordinates define the rectangle in the
overlay into which the cover is drawn.

=item C<reflection>

Enable a reflected image below the cover.  This requires the Cairo Perl
bindings.  Values from 0 through 100 control the reflection height as a
percentage; C<1> selects the historical default of 25 percent.

=item C<r_alpha1>, C<r_alpha2>, C<r_scale>

Control reflection opacity and vertical scale.

=back

Files named by C<default> and C<overlay> may be absolute or relative to
the layout search path.

=item C<ArtistPic>

Display an artist picture.  It accepts the same picture options as
C<Cover>.  With multiple artists, C<multiple=v> or C<multiple=h> can be
used to display more than one picture vertically or horizontally.

=item C<Stars>

Display and edit the current rating using star images.  C<xalign> and
C<yalign> position the stars when the widget receives more space than it
needs.

=item C<LabelsIcons>

Display icons for labels assigned to the current song.  User icons are
looked up under F<$XDG_CONFIG_HOME/jukebox/icons/> by names beginning
with C<label->.

=item C<SongInfo>

Display song properties.  Important options include C<expander>,
C<hide_empty>, C<font>, C<group>, C<markup_cat>, C<markup_field>, and
C<markup_value>.

=item C<PictureBrowser>

Display pictures from the current album directory and allow the active
picture to be changed.

=item C<AddLabelEntry>

Entry used to add labels to the current song.

=item C<LabelToggleButtons>

Toggle buttons for editing labels.  C<hide_unset=1> hides labels not
currently set on the song.

=item C<Context>

Context view implemented as a C<TabbedLists> widget with defaults suited
to context pages supplied by plugins.

=back

=head3 Miscellaneous widgets

=over

=item C<AASearch>

Artist/album search.  C<aa> selects the grouped field and C<activate>
selects the activation action.

=item C<ArtistSearch>

Equivalent to C<AASearch(aa=artists)>.

=item C<AlbumSearch>

Equivalent to C<AASearch(aa=album)>.

=item C<SongSearch>

Song search entry.

=item C<ConnectionsList>

Display active connections in GStreamer server mode.

=item C<Visuals>

Display audio visualization when supported by the GStreamer backend.

=item C<QueueActions>

Combo box used to change the action associated with queued songs.

=item C<ToggleButton>

Show or hide one or more widgets.  Common options are C<icon>, C<text>,
C<widget>, C<resize>, C<togglegroup>, C<size>, and C<relief>.  Icon names
may refer to bundled files under F</usr/share/jukebox/pix/>, Gtk2 stock
items, or user icons under F<$XDG_CONFIG_HOME/jukebox/icons/>.

=item C<Filler>

Empty widget useful with size groups.

=item C<HSeparator>, C<VSeparator>

Horizontal and vertical separators.

=item C<PlayOrderCombo>

Combo box for selecting play order.  C<minwidth> defaults to 100; C<-1>
allows unrestricted growth.

=item C<Equalizer>

Equalizer widget for backends that provide equalizer support.  Options
include C<preamp> and C<labels>.

=item C<EqualizerPresets>

Preset selector/editor.  Options include C<editmode>, C<notoggle>,
C<open>, and C<onoff>.

=item C<EqualizerPresetsSimple>

Equivalent to C<EqualizerPresets> with C<open=1> and C<notoggle=1>.

=item C<Progress>

Display active jukebox operations and hide itself when there are none.
C<compact> defaults to true.

=item C<VProgress>

Vertical variant of C<Progress>; its C<compact> option defaults to false.

=back

=head3 Song-list widgets

When a layout contains more than one song-list-like widget, all but one
should be assigned an explicit C<group>.  Widgets that interact with a
song list accept the same C<group> option so they can target the intended
list.

=over

=item C<QueueList>

Editable queue.  It accepts the same general options as C<SongList>.

=item C<PlayList>

C<SongList> in playlist mode.

=item C<SongList>

General song-list widget.  Common options include:

=over

=item C<hideif>

C<nofilter> or C<empty> can hide the list, or the widgets named by
C<hidewidget>, when the condition is true.

=item C<hidewidget>

C<|>-separated widgets to hide instead of the song list itself.

=item C<shrinkonhide>

A string of C<h>, C<v>, or C<_> entries controlling whether the window
shrinks horizontally or vertically as widgets are hidden.

=item C<mode>

C<playlist> synchronizes the widget with the playlist.

=item C<activate>

Action performed when a song is double-clicked.  Supported actions
include C<play>, C<queue>, C<queueinsert>, C<replacequeue>, C<playlist>,
C<addplay>, C<insertplay>, C<filter_and_play>, C<filter_sort_and_play>,
and C<properties>.  An action can be followed by a command, for example
C<activate=play&CloseWindow>.

=item C<activateN>

Define the double-click action for mouse button N.

=item C<headers>

C<off> hides column headers.

=item C<songypad>

Change vertical padding between rows.

=item C<no_typeahead>

Disable automatic type-ahead search when true.

=item C<rowtip>

Tooltip markup for a row.  Song variables from L</Song variables> may be
used.

=item C<autoupdate>

Keep the list sorted and filtered automatically.  It defaults to true
and is ignored for playlist, queue, and static-list modes.

=back

=item C<TabbedLists>

Song lists arranged in tabs.  Tabs may contain playlists, static lists,
the queue, layouts of type C<P>, and context pages.  Options include
C<tablist>, C<closebuttons>, C<newbutton>, C<tabpos>, C<default_child>,
and C<match>.

=item C<SongTree>

Highly customizable replacement for C<SongList>.  Many C<SongList>
options also apply, including C<activate>, C<activateN>, C<headers>, row
padding, C<rowtip>, and C<autoupdate>.  The bundled layout files contain
working group and column definitions.

=back

=head3 Widgets related to song lists

Filter numbers range from 0 through 9.  Filter 0 is conventionally used
by C<FilterLock>; setting a filter resets higher-numbered filters.  These
widgets accept C<group> when more than one song list is present.

=over

=item C<AABox>

Artist or album box containing the selected entity's name, picture, and
statistics.  C<aa> selects the grouped field.

=item C<ArtistBox>

Equivalent to C<AABox(aa=artists)>.

=item C<AlbumBox>

Equivalent to C<AABox(aa=album)>.

=item C<EditListButtons>

Buttons for removing, moving, and clearing selected songs.  C<small>
hides some labels and C<orientation=vertical> uses vertical buttons.

=item C<EmptyList>

Empty the associated list.

=item C<FilterBox>

Advanced search widget that sets a filter.

=item C<FilterLock>

Lock or unlock the current song-list filter.

=item C<FilterPane>

Multi-page filter browser.  Important options include C<nb>, C<hidebb>,
C<pages>, C<activate>, C<activateN>, C<searchbox>, C<no_typeahead>,
C<hidetabs>, C<tabmode>, and C<hscrollbar>.

=item C<PlayFilter>

Play the current song-list filter.

=item C<QueueFilter>

Enqueue the current song-list filter.

=item C<Refresh>

Reapply the current song-list filter.

=item C<ResetFilter>

Reset the current song-list filter.

=item C<ShuffleList>

Shuffle the associated list.

=item C<SimpleSearch>

Search entry for song metadata.  C<noselector=1> hides the selector and
C<activate> can name a command to run when Enter is pressed.

=item C<Total>

Display the number, duration, and size of selected, filtered, or library
songs.  Options include C<size>, C<format>, C<button>, C<relief>, and
C<noheader>.

=back

=head3 Menu-item widgets

These widgets are intended for C<MB> and C<SM> containers.

=over

=item C<HistItem>

Filter-history menu.

=item C<LSortItem>

Sort-order menu for the song list.

=item C<MainMenuItem>

Main jukebox menu.

=item C<LayoutItem>

Layout selector for layouts of type C<G+>.

=item C<MenuItem>

Custom menu item.  Options include C<text>, C<icon>, C<command>,
C<togglewidget>, C<resizeonly>, C<togglegroup>, and C<button>.

=item C<PFilterItem>

Playing-filter menu.

=item C<PSortItem>

Playing-sort-order menu.

=item C<PlayItem>

Choose a filter based on the playing title, artist, album, or filter and
follow the playing song-list option.

=item C<QueueItem>

Queue menu.

=item C<SeparatorMenuItem>

Menu separator.

=back

=head3 Widget aliases

Some widgets have been renamed.  The old names remain useful when
reading legacy layouts but new layouts should use the current names:

  Playlist   => OpenBrowser
  BContext   => OpenContext
  Date       => Year
  Label      => Text
  Vol        => VolumeIcon
  LabelVol   => Volume
  FLock      => FilterLock
  TogButton  => ToggleButton
  ProgressV  => VProgress
  FBox       => FilterBox
  Scale      => TimeSlider
  VolSlider  => VolumeSlider
  VolBar     => VolumeBar
  FPane      => FilterPane
  LabelTime  => PlayingTime

=head2 Embedded layouts

A layout can embed another layout by adding C<@layout_id> as a child of
a container.  For example:

  [example_layout]
  HBmain = Play Stop Pref
  VBmain = HBmain Title _@embedded_example

  [embedded_example]
  VBmain = Title _SongTree

Embedded layout identifiers support a restricted character set.  Keep
identifiers simple and alphanumeric when possible.

=head2 Song variables

Some layout options accept C<%>-letter and C<$>-word substitutions for
fields of the song associated with the widget's group.  For example:

  %t by %a

is equivalent to:

  $title by $artist

A C<$>-word may name any activated song field.  The traditional
single-letter substitutions are:

  t  title
  a  artist
  l  album
  d  disc
  n  track
  y  year
  C  comment
  p  play count
  P  last play
  k  skip count
  K  last skip
  g  genres
  L  labels
  m  length
  V  version, or empty when no version/subtitle is present
  S  title, or filename when no title is present
  f  raw filename including path
  u  UTF-8 display filename including path
  c  cover file
  Y  album year or years
  A  album artist, falling back to artist

C<%c> and C<%f> represent filenames and are generally not appropriate
for direct display.

=head1 SEE ALSO

L<jukebox(1)>, L<jukeboxrc(5)>, L<jukebox-plugins(7)>

The installed F</usr/share/jukebox/layouts/> files provide concrete
examples for the widgets and properties described here.

=cut

# vim: cc=72 tw=70
# End of file.
